import { PackageRepository } from "../repositories/packageRepository"

export const resolvers = {
  Query: {
    getPackages: () => PackageRepository.findAll(),
    // Align with GraphQL (parent, args) signature and schema using id
    getPackage: (_: any, { trackingNumber }: { trackingNumber: string }) =>
      PackageRepository.findByTrackingNumber(trackingNumber),
  },

  Mutation: {
    createPackage: (
      _: any,
      {
        sender,
        receiver,
        destination,
      }: { sender: string; receiver: string; destination: string }
    ) => {
      // Tracking number should be generated by the caller; fix template if generated here
      const trackingNumber = `PKG-${Date.now()}`
      return PackageRepository.create(
        trackingNumber,
        sender,
        receiver,
        destination
      )
    },
    // Align to schema updatePackageStatus(id: ID!, status: String!, location: String)
    updatePackageStatus: (
      _: any,
      { id, status }: { id: string; status: string }
    ) => PackageRepository.updateStatusById(id, status),
  },
}
